spring:
  application:
    name: gateway
  cloud:
    consul:
      discovery:
        health-check-path: /actuator/health
#  data:
#    redis:
#      port: ${REDIS_DB_PORT}
#      host: ${REDIS_DB_HOST}
server:
  port: ${SERVER_PORT}
